---
dependencies:
  - role: windows_common

galaxy_info:
  role_name: notepad_plus_plus
  author: your_name
  description: Installs Notepad++ on Windows servers
  license: MIT
  min_ansible_version: "2.10"
  platforms:
    - name: Windows
      versions:
        - 2016
        - 2019
        - 2022
  galaxy_tags:
    - windows
    - development
    - editor