---
collections:
  - name: azure.azcollection
    version: '1.15.0'
  - name: community.windows
    version: '1.13.0'
  - name: ansible.windows
    version: '1.14.0'
  - name: community.general
    version: '7.0.1'